version: "3"
services:
  webapp:
    build: ./frontend
    environment:
      - REACT_APP_NODE_ENV=production
    ports:
      - "3006:3006"

  server:
    build: ./server
    environment:
      - ENV_TYPE=production
      - DEPLOY_TYPE=app
    ports:
      - "5001:5001"
