apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: public.ecr.aws/h1c6y7g8/chinese-translation-api:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "5Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "1"
          env:
            - name: NUM_WORKERS
              value: "2"

          # env:
          #   - name: PG_HOST
          #     value: postgres-cluster-ip-service
          #   - name: PG_PORT
          #     value: "5432"
          #   - name: PGUSER
          #     value: postgres
          #   - name: PGDATABASE
          #     value: postgres
